<a href="https://colab.research.google.com/github/lomovtsevp/Mathematical-Modelling/blob/main/Matmod_PR5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats
LAMBDA = 0.6

In [ ]:
m, n = map(int,input().split())
A = []
for i in range(m):
  A.append(list(map(int,input().split())))

3 3
1 1 2
2 3 1
0 2 1


In [ ]:
def win_strategy(A):
  A = np.array(A)
  b = np.amax(A, axis = 1)
  r = []
  for i in range(A.shape[0]):
    tp = []
    for j in range(A.shape[1]):
      tp.append(b[i] - A[i][j])
    r.append(tp)
  print(A, b, r)
  Woltz = np.amax(np.amin(A, axis=1), axis=0)
  Optimism = np.amax(np.amax(A, axis=1), axis=0)
  Pessimizm = np.amin(np.amin(A, axis=1), axis=0)
  Savidge = np.amin(np.amax(r, axis=1), axis=0)
  H = np.amax(LAMBDA * np.amax(A, axis=1) + (1 - LAMBDA) * np.amin(A, axis=1), axis=0)
  return stats.mode([Woltz, Optimism, Pessimizm, Savidge, H])

In [ ]:
win_strategy(A)

[[1 1 2]
 [2 3 1]
 [0 2 1]] [2 3 2] [[1, 1, 0], [1, 0, 2], [2, 0, 1]]


ModeResult(mode=array([1.]), count=array([2]))